New UI for log card
Zentacle/snorkel-app pull request #27
Opened 2022-06-08 21:03 UTC by mjmayank

I didn't like the old design, so updated it a bit

<img width="427" alt="image" src="https://user-images.githubusercontent.com/63934597/172716585-4f103f37-8447-4bfb-9ab6-0620ab6b9f53.png">

2022-06-08 22:00 UTC, Nnanyielugo requested changes

2022-06-09 02:48 UTC, mjmayank commented on src/Screens/Logs/components/LogItem.tsx
> +    width: 100,
i considered it, but 100px seems small enough that even on the smallest screen size it should be okay, and also it fits the text next to it properly

2022-06-09 02:52 UTC, mjmayank commented
would prefer to merge as is

2022-06-09 18:36 UTC, Nnanyielugo approved these changes

2022-06-09 18:36 UTC, merged